### How to creat Array?
#### Many functions for Array 
1. np.array
2. np.zeros
3. np.ones
4. np.empty
5. np.arange (simple range and specific range bothe you can do it your requirement and your need)
6. np.arange (contime) ap is ka waqfa be de skte hain ke two figer mein kitna waqafa hon chaye
7. np.linspace(0,10,num=5) is mein two number k bech mein equel figer print ho ga
8. 

In [34]:
# with range of element
import numpy as np
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [35]:
b = np.zeros(5)
b

array([0., 0., 0., 0., 0.])

In [36]:
c = np.ones(5)
c

array([1., 1., 1., 1., 1.])

In [37]:
d = np.empty(5)
d

array([1., 1., 1., 1., 1.])

In [38]:
e = np.arange(0,20)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
#continue same like pahara 
f = np.arange(0,30,3)
f

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [40]:
# is function mein ap ko ek number say dosary number
# ke darmeyan equal fasla mele ga

g = np.linspace(0,10,num=5)
g

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [44]:
#specific dat types in array
h = np.ones(5,dtype=np.int8)
h

array([1, 1, 1, 1, 1], dtype=int8)

### How to create an array? for 2-D arrrays 


In [50]:
np.zeros((3,5)) #(here three column and 5 rowes )

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),)

In [51]:
np.ones((4,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## how to create an array ? 3-D array

In [68]:
# making and reshaping a 3D array 
np.arange(24).reshape(2,3,4,)


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])