### numpy pratice session

In [7]:
import numpy as np


# cratting a array using numpy

In [6]:
food = np.array(["somasa", "pakora", "allo"])
food

array(['somasa', 'pakora', 'allo'], dtype='<U6')

In [19]:
price = np.array([2,3,5,7,9,11,13])
price

array([ 2,  3,  5,  7,  9, 11, 13])

In [8]:
type (price)

numpy.ndarray

In [9]:
type (food)

numpy.ndarray

In [10]:
len(food)

3

In [12]:
price [0:]

array([2, 3, 5])

In [23]:
food [1]

np.str_('pakora')

In [24]:
price.mean()

np.float64(7.142857142857143)

In [27]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [28]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [36]:
# you are make spasice range like that is the tlabel
np.arange(2,32,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [49]:
# line space 
np.linspace(1,100, num= 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [52]:
# spiceify your data type
np.ones(10,dtype= np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [54]:
np.ones(10,dtype= np.float32)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

## Array function

In [9]:
a = np.array([52,43,0,64,2.4,12,88,3.0])
a  

array([52. , 43. ,  0. , 64. ,  2.4, 12. , 88. ,  3. ])

In [64]:
b = np.array([32,67,0.9,0.9,12,13,14,15,16,17,18,19,20])
b

array([32. , 67. ,  0.9,  0.9, 12. , 13. , 14. , 15. , 16. , 17. , 18. ,
       19. , 20. ])

In [62]:
# This function you will be used for sort (sequence)
a.sort()
a

array([ 0. ,  2.4,  3. , 12. , 43. , 52. , 64. , 88. ])

In [10]:
np.concatenate((a,b))

NameError: name 'b' is not defined

In [40]:
#2-D array
l = np.array([[1,2,3,4,0],[5,6,7,8,0],[9,10,11,12,0]])
l

array([[ 1,  2,  3,  4,  0],
       [ 5,  6,  7,  8,  0],
       [ 9, 10, 11, 12,  0]])

In [30]:
l.ndim

2

In [31]:
type (l)

numpy.ndarray

In [42]:
# size (number of elements)
l.size

15

In [41]:
l.shape

(3, 5)

In [59]:
m = np.arange(9)
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [60]:
m.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [72]:
# convert 1D into 2D array
o = np.array([1,2,3,4,5,6,7,8,9])
o

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
o.shape

(9,)

In [88]:
p = o[ : , np.newaxis]
p

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [89]:
p.shape

(9, 1)